alias aptup="sudo apt update"
alias aptug="sudo apt full-upgrade"
alias df="df -h"
alias du1="du -h --max-depth=1 2>/dev/null"
alias dps="docker ps -a"
alias el="exa -lg --git --group-directories-first"
alias ela="exa -lga --git --group-directories-first"
alias gssm="git stash save -p"
alias ports="sudo ss -ltnp"

